### ISSUE TITLE
New features for specific scenarios

### ISSUE THREAD

**Issue by diegocaprioli** [adamwathan/eloquent-oauth#16]
Hi Adam,

First of all, thanks for opensourcing your library. It was a great help for me.

I've forked your code for a project that I'm working on, and made some additions and updates to handle some custom scenarios that I need:

* In our webapp, Users need to be created by an admin first. We don't have to create them directly if the don't exist already in a user list. Because of this, I added a config parameter where you can configure the behavior (fail if user doesn't exist, or continue working as usual, creating the user). 
* In our case a User might NOT exist in the identity table, but do exist in the webapp users table. For other webapps this might be the case also if they allowed the user to register first directly into their app, and added oauth functionality later.
* The webapp where we are using this has it's own complex logic for saving and finding users, so I made the UserStore overridable by the client webapp. In this way the webapp can implement it's own logic for storing and finding users.

All these changes are in this fork of your library: https://github.com/emersonmedia/eloquent-oauth , in the branch "feature_em" (https://github.com/emersonmedia/eloquent-oauth/commits/feature_em).

I thought to share it as maybe these features make sense to you too. Please, if you have some time, maybe you can take a look at the code additions and see if it useful for you too? There are still some Log::info() calls, and more commits than might be needed, but I was doing changes and testing directly in an online staging server by pushing this... If some of this evolves into a pull request, I can clean it up and organize it in less commits.

Just let me know what you think. These changes make sense from my side and app... but don't know if they might be useful in general for the library.

Thanks for your time!

**Comment by adamwathan** [comment]
Cleaning up some issues today, gonna close this at the moment but still happy to merge a PR for adding the interface. Thanks Diego!
