### ISSUE TITLE
Multiple providers authentication

### ISSUE THREAD

**Issue by iamzozo** [adamwathan/eloquent-oauth#19]
Hi! First thanks for this great library! Absolutely easy to use, as you mentioned! :)

I would like to offer two authentication (ex. Google & Facebook) if it's possible. Now I implemented both. But when the "same" user using another provider, another user record will be created. Is it possible to lookup in the users table by a field (ex. email) and set the oauth_identities user_id to that if it's exists? (One user to Many provider)

**Comment by anvarstudios** [comment]
Thanks for the reply,

The idea is that if I am already regsitrado with GitHub with 123@demo.com corrre and wish to add an account more like Facebook as well with e 123@demo.com.

This can be performed without the system thinks it is a fact doubled the email, just a new beginning is associated.
