### ISSUE TITLE
Accessing data from additional scopes

### ISSUE THREAD

**Issue by cbojer** [adamwathan/eloquent-oauth#20]
Hey Adam,

Thanks a lot for the package, it really makes Oauth easy true Laravel style!

I do however have a question, in regards to using the package. When i provide additional scopes for a provider, in my example Facebook, the returned user details that i access through the login callback doesn't include the extra details that i requested permission for. 

How would i go about retrieving these extra details, e.g. the birthday of a user. Am i missing something here, or do i need to create a custom provider? And even so, how would i access the data?

**Comment by adamwathan** [comment]
You're right, this must've been an oversight on my part during a refactoring, I'm sure this was more straightforward at some point.

Going to look into this and see what I can do :) Originally you just needed to say `$details->customField` and it would work, if I remember correctly. Clearly not the case now, heh...

**Comment by adamwathan** [comment]
Alright, I remember why I originally had that scopes option.

Since this package retrieves an access token you can use for later requests to the provider's API, I wanted to make sure that the token that came back had any additional scopes you might need. It wasn't meant to handle any additional data that came back from the initial request for a user's profile information.

That being said, I've pushed an update that stores *all* raw data that comes back from that request on the `ProviderUserDetails` object, so it can be accessed however you need:

```
$details->raw()['birthday'];
```

...would get you what you need now :)

**Comment by ockam** [comment]
Hi Adam,

thanks for the raw feature, but that doesn’t allow us to add additional fields to the $profileFields property of the provider.

Can you add a config for that?

**Comment by ockam** [comment]
Only need to add the following line to the constructor of the Provider class:
```
        if (isset($config['profileFields'])) {
            $this->profileFields = array_merge($this->profileFields, $config['profileFields']);
        }
```

**Comment by adamwathan** [comment]
Ah you are specifically talking only about the LinkedIn Provider it seems, didn't catch that before. None of the other providers have that property and it's really just a special case for LinkedIn's API.

I don't think I'm really interested in adding too much built-in configuration for that sort of thing, as one of the main goals of the package is to handle normalization between providers of a specific set of common fields.

I think your original solution is actually an excellent and clean solution for your needs. Just extend the LinkedIn provider, add the fields you need (either hardcore or through config), and register it with your own service provider.

Custom LinkedIn provider:

```
class CustomLinkedInProvider extends LinkedInProvider
{
    protected $profileFields = [
        'id',
        'first-name',
        'last-name',
        'email-address',
        'picture-url',
        'plus',
        'any',
        'others',
        'you',
        'might',
        'need',
    ];
}
```

Custom service provider:

```
class CustomSocialLoginServiceProvider extends EloquentOAuthServiceProvider {

    protected $providerLookup = [
        'linkedin' => 'Your\\Custom\\LinkedInProvider',
    ];
}
```

That's literally the whole thing :+1:

**Comment by ockam** [comment]
Understood. Thanks for the sample code.
