### ISSUE TITLE
Add parameters to OAuth::authorize('provider')

### ISSUE THREAD

**Issue by dinkelburg** [adamwathan/eloquent-oauth#21]
Hi Adam, 

First, thanks for this great package.
I'm using OAuth::authorize('facebook') to open the facebook authorize screen. The screen opens fine, but i want it to have the popup layout. So basically i want to be able to add parameters to the OAuth::authorize('provider').
See https://developers.facebook.com/docs/reference/dialogs/oauth?locale=nl_NL for the possible facebook parameters.
In my case i want to add the parameter display=popup.

**Comment by adamwathan** [comment]
Hmm I don't think you can use the popup version with server-side OAuth, only with the Javascript SDK, because Facebook needs to redirect back with some data and it can't redirect from a popup back to the other tab.

**Comment by mrehayden1** [comment]
In this case 'popup' refers to the login form being rendered as a responsive webform.

Socialite has this functionality and I think it's very desirable.
