### ISSUE TITLE
Add new provider

### ISSUE THREAD

**Issue by dinhvupham90** [adamwathan/eloquent-oauth#22]
Hi Adam,
Is there a possible way for me to add a new provider to the package? I'm trying to using my own provider with this package.

**Comment by envision** [comment]
I have done a fork from this package (previous version before refactoring). It's not ready to publish yet though.

Right now I'm having problem with adding a second custom provider as the BaseProvider was constructed first time with the config from the first provider, and second time it's not instantiating with __construct method...

**Comment by adamwathan** [comment]
This should be totally possible, should be as simple as something like this in a service provider of your own:

```
OAuth::registerProvider('dogbook', $dogbookProvider);
```

Closing for now, feel free to comment back if you run into issues, happy to help.
