### ISSUE TITLE
Provider class's constructor ran only with first provider

### ISSUE THREAD

**Issue by envision** [adamwathan/eloquent-oauth#23]
Hi,

I have made an own package based on the previous version of this repo.

Now that I'm implementing a second provider I ran into problem where the Provider class' __construct method is ran only with the first provider, leaving it with the first provider's config details. I have compared this codebase to mine and they seem identical on how the they create providers... For example they are identical in registerProviders() method where is this:

    $provider 		= new $providerClass($config, $httpClient, $this->app['request']);

After doing loggings the main problem seems to be that with the second provider Provider@__construct method is not run and is left with first provider's details?

Also my code gives an error that my provider's (replaced those you have implemented) wouldn't be an instance of ProviderInterface even though I just updated them to be exactly similar in that they extend Provider class which in turn implements ProviderInterface. That was solved then I wrote " implements ProviderInterface" directly to those custom provider classes.

**Comment by envision** [comment]
Fixed. But how this isn't a problem with you?

Change this:

    $provider 		= new $providerClass($config, $httpClient, $this->app['request']);

To this:

	$provider 		= new $providerClass();
	$provider->init($config, $httpClient, $this->app['request']);

And renamed Provider's __construct to init

**Comment by adamwathan** [comment]
Hmmm I don't really understand the problem, you are calling `new $providerClass` somewhere and the constructor isn't actually being called?

Can you provide a more complete code sample? If it's an open source project by any chance, point me to relevant part of the code base and I'm happy to poke around.
