### ISSUE TITLE
Check for OAuth from different domain?

### ISSUE THREAD

**Issue by mcblum** [adamwathan/eloquent-oauth#25]
So this might be (probably is) a stupid question but we have a backend system which powers multiple sites across multiple domains. Is there a way to check whether a person has authenticated and then identify which user it is once the domain has changed? I tried changing the Laravel session domains to an array but it did not like that, so I went with OAuth.

Thanks for your great work on this.
Matt

**Comment by adamwathan** [comment]
Unfortunately I don't think it's possible in general to maintain any sort of state across multiple domains that way, just the nature of how cookies and the browser works :disappointed: 

I'm pretty sure you could do it with subdomains, but not across entirely different domains.

**Comment by mcblum** [comment]
Hm... thanks for the reply. That's too bad - can't make Angular work with the "preview" function of an unpublished post and was hoping just to read the login stuff.
