### ISSUE TITLE
Older Guzzle Version Requires Curl

### ISSUE THREAD

**Issue by mattbucci** [adamwathan/eloquent-oauth#26]
Hey Adam, I'm using this library on Google App Engine which doesn't allow curl requests. Guzzle 4.0 and removes this dependency and I'm having no issues after upgrading to guzzle 5.2 on my fork. 

Is there any reason I should be concerned or any reasoning as to why you chose such an older version of guzzle?

**Comment by adamwathan** [comment]
Just laziness, that's what was stable when I released the package originally, haha... Just updated to Guzzle 5, gonna tag a release now :)
