### ISSUE TITLE
No rows are inserted in oauth_identities 

### ISSUE THREAD

**Issue by vgomes** [adamwathan/eloquent-oauth#27]
I'm using the package in laravel 5 and I'm facing an issue. I manage to be redirected to Facebook, and being redirected back to my app, and using the closure I can see the details of the user, but I cannot login normally because no info is added to the table oauth_identities.

If I manually populate a row with the required info, all the new login attepts work properly..

Is this a normal behaviour because it's something I must manually insert or the package is supposed to do that for me?

Thanks and sorry if it is a stupid question.

**Comment by adamwathan** [comment]
Hey! Not sure what the problem could be... Could you check out this walkthrough video I put together, and see what might be different about your setup vs. what I put together?

https://vimeo.com/120085196

Are you on Laravel 4 or 5?

**Comment by vgomes** [comment]
I'm on laravel 5. 

I've been checking my user model and it's like the default one that laravel ships.

My problem, is when I got redirected back, system performs a select in DB

select * from `oauth_identities` where `provider` = ? and `provider_user_id` = ? limit 1

and performs it with the data google returns, and then, tries to create the user, but with no data, because nothing is ever stored in oauth_identities

insert into `users` (`updated_at`, `created_at`) values (?, ?)


If I catch that exception and store that info, the systems works perfectly.
Run a composer update and problem is the same: 

Installing adamwathan/eloquent-oauth (dev-laravel-5 daca55b)

**Comment by adamwathan** [comment]
What database are you using? I'm guessing the issue is you need to make the `email` and `password` columns nullable on your `users` table, since creating a user through this package results in a user with no credentials (of course, since they are logging in through a separate service).

The entry to `oauth_identities` is created *after* creating the `users` entry, because the `oauth_identities` table has a foreign key to the user's ID.

The first select is performed to see if the user already exists, if they don't create a new user, then save an OAuthIdentity for that new user.

**Comment by vgomes** [comment]
I see, that's exactly my problem. 
Thank you very much!

**Comment by adamwathan** [comment]
No prob glad I could help! :)

**Comment by aazm** [comment]
Hello! I have a problem with using both linkedin and facebook for one user... db insert fails.. is it possible to solve it somehow?

**Comment by adamwathan** [comment]
You mean using LinkedIn and Facebook for the same person and trying to make it one account? That isn't supported at the moment, maybe in the future. See this issue: https://github.com/adamwathan/eloquent-oauth/issues/19

**Comment by dipuchaudhary** [comment]
```
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.oauth_identities' doesn't exist (SQL: select * from `oauth_identities` where `provider` = github and `provider_user_id` = 34309829 limit 1)
Previous exceptions
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.oauth_identities' doesn't exist (42S02)``
```
why i'm getting this error although i've made changes in the user table email and password as nullable.
![Screenshot from 2020-05-18 17-17-04](https://user-images.githubusercontent.com/34309829/82208541-75f73480-992b-11ea-9309-f2b41fcfc0a3.png)
