### ISSUE TITLE
Will you be adding SoundCloud?

### ISSUE THREAD

**Issue by jackbarham** [adamwathan/eloquent-oauth#30]
Apologies if I have posted this in the wrong section. This is an awesome plugin and wondering if you are building in any more providers, especially SoundCloud? - Thanks.

**Comment by adamwathan** [comment]
I'll definitely add it to the list. Assuming their API is fairly standard it should be pretty painless. Feel free to submit a PR if you'd like to give it a go yourself :) The existing providers should serve as a really good starting point.

**Comment by jackbarham** [comment]
Yes, I like the way you have laid it all out, looks fairly painless. I'm still in the process of building my app (websites for musicians), but when I get to this part I'll add in some integration (if it's not done done already). Also, Mixcloud would be a good call. Great work :)

**Comment by adamwathan** [comment]
Hopefully you're using Laravel 5 :) https://github.com/adamwathan/eloquent-oauth/commit/3d6501e640a28d5484b884bcd2f02cc340c62ac9

**Comment by jackbarham** [comment]
I am indeed :)
