### ISSUE TITLE
Drop firstName and lastName in favor of fullName

### ISSUE THREAD

**Issue by adamwathan** [adamwathan/eloquent-oauth#31]
Lots of providers don't give you these separately. Currently splitting on space, super dumb. Should've done full name in the first place.

**Comment by babatundeakinse** [comment]
@adamwathan loving this addon for laravel..
I keep getting an exception even when the OAuth returns valid used data.

Any Ideas on what is going on ?

Thanks

**Comment by adamwathan** [comment]
@babatundeakinse Yikes that's no good! Can you open another issue with more information? A screenshot of the error page and any other information about your code you could share would be really helpful

**Comment by adamwathan** [comment]
Coming in SocialNorm
