### ISSUE TITLE
How to send more parameters to google?

### ISSUE THREAD

**Issue by mirago** [adamwathan/eloquent-oauth#34]
Hi I cannot seem to find a way how to send more parameters to google? E.g I need to send the request to 

https://accounts.google.com/o/oauth2/auth?
 client_id=424911365001.apps.googleusercontent.com&
 response_type=code&
 scope=openid%20email&
 redirect_uri=https://oa2cb.example.com/&
 state=security_token%3D138r5719ru3e1%26url%3Dhttps://oa2cb.example.com/myHome&
 login_hint=jsmith@example.com&
 openid.realm=example.com&
 hd=example.com

and that hd=example.com is actually what I need. I'm trying to restrict the access to specific domain. Is that currently possible? Thanks

**Comment by adamwathan** [comment]
This isn't configurable at the moment, and probably not in the cards, *but...*

It is really simple to extend the Google provider and register it yourself :) I would subclass this class:

https://github.com/adamwathan/eloquent-oauth/blob/master/src/AdamWathan/EloquentOAuth/Providers/GoogleProvider.php

...with something like this:

```php
class CustomGoogleProvider extends GoogleProvider
{
    protected $hd;

    // These too if you need them...
    // protected $loginHint;
    // protected $openIdRealm;

    public function __construct($config, HttpClient $httpClient, Input $input)
    {
        parent::__construct($config, $httpClient, $input);
        $this->hd = $config['hd'];

        // If you need others...
        // $this->hd = $config['login_hint'];
        // $this->hd = $config['open_id_realm'];
    }

    protected function buildAuthorizeQueryString($state)
    {
        $queryString = parent::buildAuthorizeQueryString($state);
        $queryString .= "&hd=".$this->hd;
        
        // Whatever else you need...
        $queryString .= "&login_hint=".$this->loginHint;
        $queryString .= "&openid.realm=".$this->openIdRealm;

        return $queryString;
    }
}
```

...then include whatever else you need in your config:

```php
		'google' => [
			'id' => 'your-client-id',
			'secret' => 'your-client-secret',
			'redirect' => 'http://example.com/redirect',
			'scope' => [],
			'hd' => 'example.com',
			'login_hint' => 'jsmith@example.com',
			'openid.realm' => 'example.com',
		],
```

You'll also need to register the provider, which should be done in a service provider somewhere:

```php
                $config = $this->app['config']->get('eloquent-oauth.providers.google');
                $customGoogle = new CustomGoogleProvider($config, new HttpClient, $this->app['request']);
                $this->app['adamwathan.oauth']->registerProvider('google', $customGoogle);
```

You'll want to make sure that runs *after* the included service provider if you want it to override the standard Google provider. I haven't looked into it myself to see if there's a way to guarantee that, but if there's not, you can always choose a different alias, like 'custom-google' and use that everywhere you would've used 'google'.

Hopefully that's straightforward enough! The main goal of the package is to normalize authentication with various providers, so I don't want to go down the path of allowing customization that's only applicable to a certain one. Much easier to just register your own provider in that case.
