### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by babatundeakinse** [adamwathan/eloquent-oauth#36]
Authorization was attempted with invalid [This Happens Even When OAuth Returns Valid User Details]
I have added the code below..
```php
try 
	    {
	        OAuth::login('facebook', function($user, $details) {

	        	var_dump($details);
	        	$checkVal =   $user->activated;
			    $user->username = strtolower ( $details->firstName . '.' . $details->lastName );
			    $user->name = $details->firstName . ' ' . $details->lastName;
			    $user->image_url = $details->imageUrl;
			    $user->email = $details->email;
			    $user->gender = $details->gender;
			    $user->activated = 1;
			    $user->save();

				$userRole = Role::where('name', '=', 'super_admin')->first();

				if($checkVal!=1)
				{
					//$userRole = Role::find(1);
			    	$user->roles()->attach($userRole);
				}
			    
			});

	    } 
	    catch (ApplicationRejectedException $e) 
	    {
	        // User rejected application
	        return Response::json(['success' => false,'message'=>'User Authorization Rejected']);
	    } 
	    catch (InvalidAuthorizationCodeException $e)
	    {
	    	return Response::json(['success' => false,'message'=>'Invalid Autorization Code']);
	        // Authorization was attempted with invalid
	        // code,likely forgery attempt
	    }

	    // Current user is now available via Auth facade
	    $user = Auth::user();

	    return Redirect::to('admin/tags');
```

**Comment by adamwathan** [comment]
Where does the error actually occur? Can you post a stack trace?

**Comment by babatundeakinse** [comment]
@adamwathan i have set my username field to unique so everytime i try to login its trying to add another user..

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'babatunde.akinse' for key 'users_username_unique' (SQL: insert into `users` (`username`, `name`, `image_url`, `email`, `gender`, `activated`, `updated_at`, `created_at`) values (babatunde.akinse, Babatunde Akinse, https://graph.facebook.com/10206366056218512/picture, akinsetunde10@gmail.com, , 1, 2015-02-24 12:52:57, 2015-02-24 12:52:57))' in /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:614
Stack trace:
#0 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(570): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(359): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#2 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(316): Illuminate\Database\Connection->statement('insert into `us...', Array)
#3 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `us...', Array)
#4 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1713): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `us...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(933): call_user_func_array(Array, Array)
#7 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1624): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1624): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1594): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1500): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /home/tumaxide/public_html/debug/app_laravel/app/Http/Controllers/SocialController.php(64): Illuminate\Database\Eloquent\Model->save()
#12 /home/tumaxide/public_html/debug/app_laravel/vendor/adamwathan/eloquent-oauth/src/Authenticator.php(26): App\Http\Controllers\SocialController->App\Http\Controllers\{closure}(Object(App\Models\User), Object(AdamWathan\EloquentOAuth\ProviderUserDetails))
#13 /home/tumaxide/public_html/debug/app_laravel/vendor/adamwathan/eloquent-oauth/src/OAuthManager.php(41): AdamWathan\EloquentOAuth\Authenticator->login('facebook', Object(AdamWathan\EloquentOAuth\ProviderUserDetails), Object(Closure))
#14 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): AdamWathan\EloquentOAuth\OAuthManager->login('facebook', Object(Closure))
#15 /home/tumaxide/public_html/debug/app_laravel/app/Http/Controllers/SocialController.php(75): Illuminate\Support\Facades\Facade::__callStatic('login', Array)
#16 /home/tumaxide/public_html/debug/app_laravel/app/Http/Controllers/SocialController.php(75): AdamWathan\EloquentOAuth\Facades\OAuth::login('facebook', Object(Closure))
#17 [internal function]: App\Http\Controllers\SocialController->Login()
#18 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#19 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('Login', Array)
#20 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\SocialController), Object(Illuminate\Routing\Route), 'Login')
#21 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\SocialController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Login')
#27 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'Login')
#28 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(131): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#29 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/tumaxide/public_html/debug/app_laravel/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /home/tumaxide/public_html/debug/app_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57 /home/tumaxide/public_html/debug/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58 {main}

**Comment by adamwathan** [comment]
Is it only with Facebook, or other providers as well? Is it happening when you login twice with the same Facebook account, or is it complaining when logging in with 2 different Facebook accounts?

I noticed in your code you are setting the username to be "firstname.lastname", if you have a unique constraint on that column this is gonna give you troubles because you're going to run into collisions on common names.

If this is still just in development, try clearing out the users and oauth_identities tables and see if you can replicate the error with all `dd()`s or `var_dump(); exit;`s removed. You might have accidentally created a situation where something was kinda half-saved and now it doesn't know there's already an existing user.

I see it's trying to create a user with the username "b.b", maybe there was already a user with that username in your `users` table before initial login? I would never rely on any data from `$details` being unique except `$details->id`, definitely have to be careful there.

**Comment by sath26** [comment]
same error occured with me too!! i checked authorization link in facebook developers setting its right but i get the error for social norm with invalidauthorization code exception. i removed the users from database and tried it again same errror
