### ISSUE TITLE
Field 'name' doesn't have a default value

### ISSUE THREAD

**Issue by notflip** [adamwathan/eloquent-oauth#40]
Hi,

I'm getting the  following error.
```
    SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `users` (`updated_at`, `created_at`) values (2015-03-10 22:46:19, 2015-03-10 22:46:19))
```
This is the 'simple' code i'm using

```
public function authorize()
    {
        return OAuth::authorize('facebook');
    }

    public function login()
    {
        try {
            Oauth::login('facebook');
        } catch(ApplicationRejectedException $e) {
            // Add errors if users reject
        } catch(InvalidAuthorizationCodeException $e) {
            // Add errors if csrf
        }

        //$user = Auth::user();
        //return Redirect::intended();
    }
```

Any idea what might be going wrong? Thanks!

**Comment by notflip** [comment]
Solution.

I was referencing the following
    $user = Auth::user();

But since it's Laravel 5 it should be
    $user = \Auth::user();

Unless you add the following at the top
    use Auth;

**Comment by notflip** [comment]
Edit: The solution I mentionned didn't work, anyone else having trouble with this?

**Comment by adamwathan** [comment]
Hey, it sounds like you have a non-nullable `name` column in your users table right?

The solution is either to make the field nullable, or give it a value when you log the user in:

```php
public function login()
{
    try {
        OAuth::login('facebook', function ($user, $details) {
            $user->name = $details->firstName . ' ' . $details->lastName;
            $user->save()
        });
    } catch(ApplicationRejectedException $e) {
        // Add errors if users reject
    } catch(InvalidAuthorizationCodeException $e) {
        // Add errors if csrf
    }
    return Redirect::intended();
}
```

**Comment by notflip** [comment]
Hmh.

Now it's returning null.
I have the following code as a test.

´´´
 try {
            OAuth::login('facebook', function($user, $details){
                dd($user);
            });

**Comment by notflip** [comment]
"Call to a member function save() on null", So it seems like facebook is always returning NULL.. strange!

**Comment by notflip** [comment]
I'm having an issue with the $user

This is my error when i'm using your code.
    
    Creating default object from empty value

On line 20: 

    $user->name = $details->firstName . ' ' . $details->lastName;

Thank you!

**Comment by adamwathan** [comment]
Hmmm that's odd, I'm not sure what would be causing that. Is the project open source by any chance? Can you dd() $user in the closure and ensure it's null, and if so maybe try and trace down where it's coming from?

**Comment by notflip** [comment]
What should user normally return? A new instance of a user object? or
model?
Thank you!

2015-03-12 2:32 GMT+01:00 Adam Wathan <notifications@github.com>:

**Comment by adamwathan** [comment]
It should be a new or existing instance of User depending on if the person has ever logged in before :/

**Comment by notflip** [comment]
U bent uitgenodigd!

Met Airbnb kun je unieke accommodaties bij lokale verhuurders ontdekken, over de hele wereld.
Het is simpel, meld je voor 20 mei 2015 aan om €22 korting te krijgen op je eerste reis van €89 of meer.


Claim je €22 tegoed
http://www.airbnb.be/c/mstevens1?euid=b737f501-7fbd-72e4-41be-7026b940a9b5&ri=18292264&s=1

Bedankt,
Het Airbnb Team

Postbus 410807, San Francisco, CA 94121

Afmelden
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAzZjQ0ZDBmZTFiMzc0ZTY3YjkzZWQwYzFkNDdmMzg2Njc5MzgzZTA1NjVmNzczOTJjZjAwMDAwMDAxMTExOGFlYjY5MmExNjljZTAzOWM2YzQ1QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiJiNzM3ZjUwMS03ZmJkLTcyZTQtNDFiZS03MDI2Yjk0MGE5YjUifQ==&mac=TrOi7Wf6ER3QLhBW-A8vvEyQXyE=

### Airbnb ###
