### ISSUE TITLE
Saving gender, about, location, languages

### ISSUE THREAD

**Issue by Hjsurk** [adamwathan/eloquent-oauth#44]
Is it possible to use the extra permissions with Eloquent-OAuth? My app uses user_about_me, user_birthday and user_location as extra permissions. I would like to save the about, birthday, languages and city of a person with these.

My current code looks like this but doesn't put anything but the username, email, first_name, last_name and avatar in the table.

Facebook asks to use these permissions when I login, but doesn't seem to use them after that.

<b>Routes.php</b>

```php
Route::get('facebook/login', function() {
    try {
        OAuth::login('facebook', function($user, $details) {
            $user->username = $details->firstName . ' ' . $details->lastName;
            $user->email = $details->email;
            $user->first_name = $details->firstName;
            $user->last_name = $details->lastName;
            $user->birthday = $details->birthday;
            $user->avatar = $details->imageUrl;
            $user->gender = $details->gender;
            $user->about = $details->about;
            $user->city = $details->location;
            $user->lang = $details->languages;
            $user->save();
        });
    } catch (ApplicationRejectedException $e) {
        // User rejected application
    } catch (InvalidAuthorizationCodeException $e) {
        // Authorization was attempted with invalid
        // code,likely forgery attempt
    }

    // Current user is now available via Auth facade
    $user = Auth::user();

    return Redirect::intended();
});
```

<b>eloquent-oauth.php</b>
<i>Facebook</i>
```php
'scope' => ['email', 'public_profile',  'user_about_me', 'user_birthday', 'user_location'],
```

**Comment by adamwathan** [comment]
Hey, yeah you can access the raw Facebook data like so:

```php
        OAuth::login('facebook', function($user, $details) (
            $user->gender = $details->raw()['gender']; // Or whatever the key is
            $user->save();
        });
```

Do a `dd($details->raw())` in the closure to see everything that's available. Obviously you can't trust those keys to be there for every provider but if you need access to the raw information from a specific provider this is how you'd do it.

**Comment by Hjsurk** [comment]
Thanks, that worked perfectly! :+1:
