### ISSUE TITLE
Oauth with Facebook depreciated

### ISSUE THREAD

**Issue by Metrakit** [adamwathan/eloquent-oauth#54]
Hi,
Thanks for your package.

When I'm using your package with the Facebook API I'm getting a warning "You must upgrade this app to Graph API v2.x
v1.0 will be deprecated on April 30, 2015"

I'm using the version for Laravel 4.

Are you going to update your package for the new API from Facebook ?

Thanks.

**Comment by adamwathan** [comment]
I was dreading things like this :) I will get that update in ASAP, thanks for letting me know!

**Comment by Metrakit** [comment]
You're welcome.

Thanks to you.

**Comment by adamwathan** [comment]
Keep it open for now until I fix it! :)

**Comment by adamwathan** [comment]
Tagged a new release (v4.0.2) which uses Graph API 2.0, please give it a try and let me know if there are any issues!

**Comment by Metrakit** [comment]
Ok Thanks ! I will soon when I back home

**Comment by mhluzi** [comment]
Hi 

Thanks for the awesome package!

I am using Laravel 5 and was wondering if I could implement the FB changes in that version?
(True Confession: I have tried bludgeoning the FaceBookProvider.php code into place but get an "Undefined property: AdamWathan\EloquentOAuth\Providers\FacebookProvider::$request" on that page line 32)

Currently I am sweetly logging in via LinkedIn so really pleased with the package so far.
c:

**Comment by mhluzi** [comment]
Ooooh. Okay so this is working for me :
Basically in FacebookProvider.php [tagged as (v4.0.2)]  I  changed line 32 

from:
'code' => $this->request->authorizationCode(),
to
'code' => $this->getAuthorizationCode(),

and that works for Laravel 5

Hope that helps someone!

**Comment by adamwathan** [comment]
@mhluzi Wow can't believe I hadn't updated both, d'oh! Updated the v5 version as well now:

https://github.com/adamwathan/eloquent-oauth/releases/tag/v5.0.2
