### ISSUE TITLE
Question: OAuth but not for a user?

### ISSUE THREAD

**Issue by ssssteve** [adamwathan/eloquent-oauth#59]
Hi,

I'm trying to implement OAuth2 for a google account so we can access Google Analytics. My problem is that it's a single company-wide google account, so we'll be trying to log in with OAuth _after_ a user has logged in to the Laravel 5 app itself, and therefore AIUI we need to keep the OAuth user out of Auth. Is this possible?

Many thanks.

**Comment by adamwathan** [comment]
Hey Steve! This package is really just meant to handle authentication with different OAuth providers in a unified way. If you need more complex integration with a provider (like Google in your case) and need to make specific API calls, your best bet is to use a package like this one: https://github.com/google/google-api-php-client

**Comment by ssssteve** [comment]
OK, thanks very much, I thought that this might be the only way, but thought I'd try existing packages first.
