### ISSUE TITLE
Serviceprovider for Laravel disappeared?

### ISSUE THREAD

**Issue by syphernl** [adamwathan/eloquent-oauth#60]
In 5.0.2 it appears that things have changed which causes existing apps to break when they update to this version since the ServiceProvider is missing. 

It is a tag, but the readme doesn't specify that this should be used.

**Comment by adamwathan** [comment]
Yikes I goofed, I'm going to drop the tag for now, thanks for the quick issue!

**Comment by adamwathan** [comment]
Should be good now, I had tagged it against `master` instead of the `laravel-5` branch. Let me know if that resolves your issue and I can close this off. Thanks again for letting me know so quickly!

**Comment by syphernl** [comment]
Whoops :-) 

After removing the folder from the `vendor/` and re-running `composer update` it works again as it should. Composer didn't see the change without it.

All seems to be working fine again.

Thanks!
