### ISSUE TITLE
can not authorize

### ISSUE THREAD

**Issue by axejane** [adamwathan/eloquent-oauth#62]
laravel 4.1
"adamwathan/eloquent-oauth": "~4.0"

ErrorException
Undefined property: AdamWathan\EloquentOAuth\Providers\FacebookProvider::$request

  $url = $this->getAccessTokenBaseUrl();
        try {
            $response = $this->httpClient->get($url, [
                'query' => [
                    'client_id' => $this->clientId,
                    'client_secret' => $this->clientSecret,
                    'redirect_uri' => $this->redirectUri(),
                    'code' => $this->request->authorizationCode(), // this line 
                ],
            ]);

**Comment by adamwathan** [comment]
Should be fixed in v4.0.3, I fixed this a while ago but I guess I never tagged a release :( So bad at open source.
