### ISSUE TITLE
Not catching ApplicationRejectedException when user reject facebook login

### ISSUE THREAD

**Issue by mak1986** [adamwathan/eloquent-oauth#69]
I'm getting an error page showing that an ApplicationRejectedException has been thrown.
Am I doing anything wrong here? It catches the exception when I do the catch on runtimeException.

![screencapture-localhost-gu-public-facebook-login-1433529557920](https://cloud.githubusercontent.com/assets/7188855/8012691/8d6973f6-0bed-11e5-9e2b-d1a3da3aa8ce.png)

Here's my code

```php
Route::get('{oauth}/login', function($oauth) {
    try {
        OAuth::login($oauth);
    } catch (ApplicationRejectedException $e) {
        echo "in ApplicationRejectedException";
        die();
    } catch (InvalidAuthorizationCodeException $e) {
        // Authorization was attempted with invalid
        // code,likely forgery attempt
    }
   //catch(\RuntimeException $e){
   //     echo "in RuntimeException";
   //     die();
   //}

    // Current user is now available via Auth facade
    $user = Auth::user();

    return Redirect::intended();
});
```

**Comment by adamwathan** [comment]
Can you double check that you are importing the `ApplicationRejectedException` from the correct namespace?

**Comment by mak1986** [comment]
Thank you :)
It was the namespace. 

I changed from 
use \AdamWathan\EloquentOAuth\Exceptions\ApplicationRejectedException;
to
use \SocialNorm\Exceptions\ApplicationRejectedException;

and that fixed it.

**Comment by adamwathan** [comment]
Great! I'll make sure to update the documentation. Thanks!



—
Adam
