### ISSUE TITLE
Class 'OAuth' not found

### ISSUE THREAD

**Issue by jerauf** [adamwathan/eloquent-oauth#74]
I get the error "Class 'OAuth' not found" when I try to authenticate using Facebook.

I'm following your instructions and looking at your 5.1 example. Seems like I followed everything.

Do I need to make a change somewhere?

**Comment by adamwathan** [comment]
This came up recently here: https://github.com/adamwathan/eloquent-oauth-l5/issues/5

Quickest fix for now is to use a different alias in `config/app.php` for the facade. I'm going to update this in the next release, probably go with something like `SocialAuth`.

**Comment by jrean** [comment]
@adamwathan maybe you should add a quick "hot" note on the home page README until your patch.
