### ISSUE TITLE
Retrieving The Authenticated User

### ISSUE THREAD

**Issue by ertanercan** [adamwathan/eloquent-oauth#83]
I was trying to use  Auth::attempt() without password but I couldn't make it.
So
I hacked Authenticator.php just to give ability to check user activated or not. Here is ugly solution from me

   
     public function login($providerAlias, $userDetails, $callback = null)
     {
         $user = $this->getUser($providerAlias, $userDetails);
         $user = $this->runCallback($callback, $user, $userDetails);
         $this->updateUser($user, $providerAlias, $userDetails);

        //check if login access true
        if ($user->loginAccess) {
            $this->auth->login($user);
        }
        
    }

**Comment by adamwathan** [comment]
What do you mean exactly? Where and how were you trying to use Auth::attempt()?

**Comment by ertanercan** [comment]
Apologies If I wasn't clear.My aim just to find solution to stop user to sign in,  strait to use app.Instead I added loginAccess field to user model and if " Super Admin"  give permission to person then can sign in and use the web application. I notice that you don't use Auth::attempt() to login person because of password field is empty.
