### ISSUE TITLE
Running something on register

### ISSUE THREAD

**Issue by m1guelpf** [adamwathan/eloquent-oauth#88]
I have a [MailController](https://github.com/m1guelpf/laragit/blob/master/app/Http/Controllers/MailController.php) to send a welcome message to new users.
I also have a [LoginController](https://github.com/m1guelpf/laragit/blob/master/app/Http/Controllers/LoginController.php) to login/register the user via Github.
How can I run the welcome message function **ONLY** on register and not on login?
Thank you!

**Comment by adamwathan** [comment]
Hey @m1guelpf, you should be able to check the public `$exists` property on the model that is passed in to the callback to know if it has been saved or not:

```
SocialAuth::login('facebook', function ($user, $details) {
    if (! $user->exists) {
        // Send welcome email
    }
});
```
